### ISSUE TITLE
EventMobi Contract

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#67]
```[tasklist]
### Tasks
- [ ] Have Nell review EventMobi contract [sent to Nell 3/27/24]
- [ ] Southern Cross signs contract
- [ ] Axim pays 50% deposit
```
