### ISSUE TITLE
EventMobi App Setup Tasks

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#68]
Hi @davidw-sa and @parttechdev - this is the main ticket where I'm tracking the EventMobi to-do tickets.

The tasks we'll need to do to get information to the EventMobi team for app setup. [EventMobi shared drive folder](https://drive.google.com/drive/folders/1y1LtYYL2BEuldra1jGb3A7m4o9PSLdTW).
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/conference-planning-2024/issues/76
- [ ] https://github.com/openedx/conference-planning-2024/issues/79
- [ ] https://github.com/openedx/conference-planning-2024/issues/74
- [ ] https://github.com/openedx/conference-planning-2024/issues/75
- [ ] https://github.com/openedx/conference-planning-2024/issues/77
- [ ] https://github.com/openedx/conference-planning-2024/issues/78
- [ ] https://github.com/openedx/conference-planning-2024/issues/73
```

**Comment by parttechdev** [comment]
@mphilbrick211 please can you either send me the font's used in the artwork or provide their names.

**Comment by mphilbrick211** [comment]
@cassiezamparini can you help with this?

**Comment by cassiezamparini** [comment]
@mphilbrick211 I'm trying to see which fonts are being referred to... @parttechdev can you send me screenshots for better context?

**Comment by davidw-sa** [comment]
This would be any preferred fonts you would like to use in the design of
the app.

Kind regards,

David Wilson
Participate Technologies

**Comment by cassiezamparini** [comment]
@davidw-sa Okay great. Please use [Inter](https://fonts.google.com/specimen/Inter) 😄

**Comment by parttechdev** [comment]
Yes, this is perfect, thanks!
