### ISSUE TITLE
Stellenbosch Venue Contract

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#69]
```[tasklist]
### Tasks
- [ ] Nell reviews contract [Nell reviewing final draft 3/27/24]
- [ ] Peter to sign the contract on behalf of Axim
- [ ] 50% deposit to be paid
```
